version: '3.8'

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: ada_postgres
    environment:
      POSTGRES_USER: ada_user
      POSTGRES_PASSWORD: ada_password
      POSTGRES_DB: ada_compliance
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ada_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ada_api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./models:/app/models
      - ./reports:/app/reports
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ada_user:ada_password@postgres:5432/ada_compliance
      - MODEL_PATH=/app/models/yolov8x-ada.pt
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy

  # Streamlit Dashboard
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: ada_streamlit
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
      - ./models:/app/models
      - ./reports:/app/reports
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://ada_user:ada_password@postgres:5432/ada_compliance
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

volumes:
  postgres_data:
